language: generic
sudo: required
services:
    - docker


before_install:
    - docker build -t  naferes/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true  naferes/docker-react npm run test -- --coverage 