version: '3'
services:
    web: 
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: >
            bash -c "chown node:node -R ./node_modules/ && npm start"
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests: 
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: >
            bash -c "chown node:node -R ./node_modules/ && npm run test"
        volumes: 
            - /app/node_modules
            - .:/app